export const CAR_BRANDS: Record<string, string[]> = {
  Toyota: ['Corolla','Camry','Yaris','Land Cruiser','Prado','RAV4','Rush','Fortuner','Innova','Avanza','HiAce','Hilux','C-HR'],
  Nissan: ['Sunny','Sentra','Altima','X-Trail','Patrol','Navara','Micra','Kicks','Qashqai','Pathfinder','Murano','Armada'],
  Honda: ['Civic','Accord','HR-V','CR-V','Pilot','Jazz','BR-V','City'],
  Mitsubishi: ['Lancer','Outlander','Pajero','L200','Eclipse Cross','ASX','Attrage','Xpander'],
  Suzuki: ['Swift','Vitara','Ertiga','Jimny','Dzire','Ciaz','Baleno'],
  Mazda: ['Mazda2','Mazda3','Mazda6','CX-3','CX-5','CX-9','BT-50'],
  Subaru: ['Outback','Forester','Impreza','XV','Legacy'],
  Hyundai: ['Elantra','Tucson','Sonata','i10','i20','i30','Santa Fe','Accent','Creta','Venue','Palisade','Staria'],
  Kia: ['Cerato','Sportage','Sorento','Picanto','Rio','Carnival','Seltos','K5','Telluride','EV6'],
  Genesis: ['G70','G80','G90','GV70','GV80'],
  SsangYong: ['Rexton','Tivoli','Korando'],
  Chevrolet: ['Optra','Cruze','Captiva','Aveo','Malibu','Traverse','Tahoe','Silverado','Trailblazer','Spark'],
  Ford: ['Focus','Fiesta','Fusion','Explorer','F-150','Edge','EcoSport','Ranger','Bronco','Mustang','Expedition'],
  Jeep: ['Wrangler','Cherokee','Grand Cherokee','Compass','Renegade','Gladiator'],
  Dodge: ['Charger','Challenger','Durango','RAM 1500'],
  Cadillac: ['CT4','CT5','Escalade','XT4','XT5','XT6'],
  GMC: ['Yukon','Suburban','Sierra','Canyon','Terrain','Acadia'],
  BMW: ['1 Series','2 Series','3 Series','4 Series','5 Series','7 Series','X1','X2','X3','X4','X5','X6','X7','M3','M5','iX'],
  'Mercedes-Benz': ['A-Class','B-Class','C-Class','E-Class','S-Class','GLA','GLB','GLC','GLE','GLS','G-Class','AMG GT'],
  Audi: ['A1','A3','A4','A6','A8','Q2','Q3','Q5','Q7','Q8','e-tron'],
  Volkswagen: ['Golf','Passat','Tiguan','Polo','Touareg','Jetta','T-Roc','ID.4'],
  Skoda: ['Octavia','Superb','Kodiaq','Karoq','Fabia'],
  Porsche: ['911','Cayenne','Macan','Panamera','Taycan'],
  'Land Rover': ['Discovery','Defender','Range Rover','Range Rover Sport','Evoque','Freelander'],
  Jaguar: ['XE','XF','XJ','F-Pace','E-Pace','F-Type'],
  Volvo: ['S60','S90','V60','XC40','XC60','XC90'],
  Peugeot: ['208','301','308','408','2008','3008','5008'],
  Renault: ['Logan','Symbol','Duster','Megane','Clio','Captur','Koleos'],
  Fiat: ['Tipo','500','Bravo','500X'],
  Opel: ['Astra','Corsa','Mokka','Grandland','Insignia'],
  'Alfa Romeo': ['Giulia','Stelvio','Tonale'],
  Lexus: ['IS','ES','LS','NX','RX','GX','LX','UX'],
  Infiniti: ['Q50','Q60','QX50','QX60','QX80'],
  MG: ['MG3','MG5','MG6','MG ZS','MG HS','MG RX5','MG RX8','Cyberster'],
  Chery: ['Tiggo 4','Tiggo 4 Pro','Tiggo 7','Tiggo 7 Pro','Tiggo 8','Tiggo 8 Pro','Arrizo 5','Arrizo 6','Arrizo 8'],
  Jetour: ['Dashing','X70','X70 Plus','X90','X90 Plus','T2','Traveler'],
  Haval: ['H6','H2','Jolion','F7','F7x','Dargo','H9'],
  BYD: ['Atto 3','Han','Tang','Dolphin','Seal','Song Plus','Yuan Plus'],
  Geely: ['Emgrand','Coolray','Tugella','Okavango','Preface'],
  GAC: ['GS3','GS4','GS8','GA4','Empow'],
  BAIC: ['X35','X55','X7','BJ40','EU5'],
  JAC: ['J7','S3','S4','T8','E10X'],
  Tank: ['300','400','500'],
  OMODA: ['5','C5'],
  Other: ['Other'],
}

export const BRAND_NAMES = Object.keys(CAR_BRANDS).sort()
