'use client'

import Header from '@/components/Header'
import Footer from '@/components/Footer'

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#FAF9F6' }}>
      <Header />
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '80px 24px 80px' }}>
        <p style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, letterSpacing: '0.3em', color: '#D4A843', textTransform: 'uppercase', marginBottom: 16 }}>
          — Legal
        </p>
        <h1 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: 44, fontWeight: 400, color: '#2C3A6B', marginBottom: 8 }}>Privacy Policy</h1>
        <p style={{ fontSize: 13, color: '#9ca3af', marginBottom: 40 }}>Last updated: May 2026</p>

        {[
          { title: 'Information We Collect', body: 'We collect information you provide when registering (name, phone number, nationality, email) and information generated by your use of the platform (listings viewed, contacts initiated, areas of interest).' },
          { title: 'How We Use Your Information', body: 'Your information is used to: provide and improve our services, connect you with property owners or service providers you choose to contact, send relevant notifications (only if you opt in), and maintain platform security.' },
          { title: 'Information Sharing', body: 'When you initiate contact with a property owner or service provider, your contact information may be shared with that party to facilitate the connection. We do not sell your personal data to third parties.' },
          { title: 'Data Security', body: 'We use industry-standard security practices including encrypted connections (HTTPS), secure authentication, and row-level security on our database. Your password is never stored in plain text.' },
          { title: 'Ratings & Reviews', body: 'Reviews you submit for service providers are associated with your account. Your full name is never shown publicly — only your first name and last initial.' },
          { title: 'Cookies', body: 'We use minimal cookies required for authentication and session management. We do not use advertising cookies or sell browsing data.' },
          { title: 'Your Rights', body: 'You can request deletion of your account and associated data at any time by contacting us at hello@dredott.com. Listings associated with your account will be removed within 30 days.' },
          { title: 'Contact', body: 'For privacy-related questions, contact us at hello@dredott.com.' },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: 28 }}>
            <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: 22, color: '#2C3A6B', marginBottom: 8 }}>{section.title}</h2>
            <p style={{ fontSize: 14, color: '#4b5563', lineHeight: 1.8 }}>{section.body}</p>
          </div>
        ))}
      </div>
      <Footer />
    </div>
  )
}